import Head from 'next/head'

import Header from '../components/Header'
import Banner from '../components/Banner'
import ProductFeed from'../components/ProductFeed'
import ShowCase from '../components/showcase'

export default function Home({products}) {
  return (
    <div className="bg-light_gray pb-20">
      <Head>
        <title>Daraz Clone 1.0 | Online Shopping Sri Lanka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div class="grid justify-items-center">
        <div>1</div>
      </div> */}
      <Header />

      <main className="max-w-screen-xl mx-auto">
        {/* banner */}
        <Banner />

        <div className="mt-10 flex relative">
          <h2 className="font-bold text-xl ">Flash Sale</h2>
          <button className="p-1 absolute top-2 right-2 text-primaryclr border-2 border-primaryclr">SHOP MORE</button>
        </div>

        {/* Products */}
        <ProductFeed products={products}/>

        <ShowCase />
        
      </main>

      
    </div>
  )
}


export async function getServerSideProps(context){

  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
      products,
    }
  };

}
